"""Final DOB

Revision ID: 3403a78508a2
Revises: 79757fef89ca
Create Date: 2018-03-24 17:56:29.070423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3403a78508a2'
down_revision = '79757fef89ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_information_dob'), 'information', ['dob'], unique=False)
    op.create_index(op.f('ix_information_phone'), 'information', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_information_phone'), table_name='information')
    op.drop_index(op.f('ix_information_dob'), table_name='information')
    # ### end Alembic commands ###
