"""Documents Table

Revision ID: 4798fc64ab0c
Revises: 2b7b08def94c
Create Date: 2018-03-24 17:33:10.258211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4798fc64ab0c'
down_revision = '2b7b08def94c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('aadhar', sa.String(length=100), nullable=True),
    sa.Column('tenth', sa.String(length=100), nullable=True),
    sa.Column('twelfth', sa.String(length=100), nullable=True),
    sa.Column('domicile', sa.String(length=100), nullable=True),
    sa.Column('birth', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_aadhar'), 'documents', ['aadhar'], unique=False)
    op.create_index(op.f('ix_documents_birth'), 'documents', ['birth'], unique=False)
    op.create_index(op.f('ix_documents_domicile'), 'documents', ['domicile'], unique=False)
    op.create_index(op.f('ix_documents_tenth'), 'documents', ['tenth'], unique=False)
    op.create_index(op.f('ix_documents_twelfth'), 'documents', ['twelfth'], unique=False)
    op.add_column(u'information', sa.Column('dob', sa.Date(), nullable=True))
    op.create_index(op.f('ix_information_dob'), 'information', ['dob'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_information_dob'), table_name='information')
    op.drop_column(u'information', 'dob')
    op.drop_index(op.f('ix_documents_twelfth'), table_name='documents')
    op.drop_index(op.f('ix_documents_tenth'), table_name='documents')
    op.drop_index(op.f('ix_documents_domicile'), table_name='documents')
    op.drop_index(op.f('ix_documents_birth'), table_name='documents')
    op.drop_index(op.f('ix_documents_aadhar'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
