"""VirtualID_Table

Revision ID: 4e2735589bed
Revises: 600df95f14f4
Create Date: 2018-03-25 19:35:59.880502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e2735589bed'
down_revision = '600df95f14f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('virtualID',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('virtual_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_virtualID_virtual_id'), 'virtualID', ['virtual_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_virtualID_virtual_id'), table_name='virtualID')
    op.drop_table('virtualID')
    # ### end Alembic commands ###
