"""Unique Phone No

Revision ID: 600df95f14f4
Revises: 3403a78508a2
Create Date: 2018-03-24 17:58:51.232455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '600df95f14f4'
down_revision = '3403a78508a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_information_phone', table_name='information')
    op.create_index(op.f('ix_information_phone'), 'information', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_information_phone'), table_name='information')
    op.create_index('ix_information_phone', 'information', ['phone'], unique=False)
    # ### end Alembic commands ###
