"""Added Phone Number

Revision ID: 79757fef89ca
Revises: 4798fc64ab0c
Create Date: 2018-03-24 17:44:36.378227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79757fef89ca'
down_revision = '4798fc64ab0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('information', sa.Column('phone', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_information_phone'), 'information', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_information_phone'), table_name='information')
    op.drop_column('information', 'phone')
    # ### end Alembic commands ###
